{
	"type":"record",
	"name":"Customer",
	"fields": [{
			"name":"duration",
			"type":"int"
		   },
		   {
			"name":"protocol_type",
			"type":"string"
		   },
		   {
			"name":"service",
			"type":"string"
		   },
		   {
			"name":"flag",
			"type":"string"
		   },
		   {
			"name":"src_bytes",
			"type":"int"
		   },
		   {
			"name":"dst_bytes",
			"type":"int"
		   },
		   {
			"name":"land",
			"type":"int"
		   },
		   {
			"name":"wrong_fragment",
			"type":"int"
		   },
		   {
			"name":"urgent",
			"type":"int"
		   },
		   {
			"name":"hot",
			"type":"int"
		   },
		   {
			"name":"num_failed_logins",
			"type":"int"
		   },
		   {
			"name":"logged_in",
			"type":"int"
		   },
		   {
			"name":"num_compromised",
			"type":"int"
		   },
	           {
			"name":"root_shell",
			"type":"int"
		   },
		   {
			"name":"su_attempted",
			"type":"int"
		   },
		   {
			"name":"num_root",
			"type":"int"
		   },
		   {
			"name":"num_file_creations",
			"type":"int"
		   },
		   {
			"name":"num_shells",
			"type":"int"
		   },
		   {
			"name":"num_access_files",
			"type":"int"
		   },
		   {
			"name":"num_outbound_cmds",
			"type":"int"
		   },
		   {
			"name":"is_host_login",
			"type":"int"
		   },
		   {
			"name":"is_guest_login",
			"type":"int"
		   },
		   {
			"name":"count",
			"type":"int"
		   },
		   {
			"name":"srv_count",
			"type":"float"
		   },
		   {
			"name":"serror_rate",
			"type":"float"
		   },
		   {
			"name":"srv_serror_rate",
			"type":"float"
		   },
		   {
			"name":"rerror_rate",
			"type":"float"
		   },
		   {
			"name":"srv_rerror_rate",
			"type":"float"
		   },
		   {
			"name":"same_srv_rate",
			"type":"int"
		   },
		   {
			"name":"diff_srv_rate",
			"type":"int"
		   },
		   {
			"name":"srv_diff_host_rate",
			"type":"float"
		   },
		   {
			"name":"dst_host_count",
			"type":"float"
		   },
		   {
			"name":"dst_host_srv_count",
			"type":"float"
		   },
		   {
			"name":"dst_host_same_srv_rate",
			"type":"float"
		   },
		   {
			"name":"dst_host_diff_srv_rate",
			"type":"float"
		   },
		   {
			"name":"dst_host_same_src_port_rate",
			"type":"float"
		   },
		   {
			"name":"dst_host_srv_diff_host_rate",
			"type":"float"
		   },
		   {
			"name":"dst_host_serror_rate",
			"type":"float"
		   },
		   {
			"name":"dst_host_srv_serror_rate",
			"type":"float"
		   },
		   {
			"name":"dst_host_rerror_rate",
			"type":"float"
		   },
		   {
			"name":"dst_host_srv_rerror_rate",
			"type":"string"
		   }]
}

